Revert "Do not pull all enums. Use the lookup facility."
This reverts commit 2b071027162fb23bbe78e90723734bc7654dcd1a.

Try to appease the incremental builds. They fail with:

In file included from test_Persistency1_C_ACLiC_dict dictionary payload:7:
./test_Persistency1.C:69:8: error: redefinition of 'Event'
struct Event : public DataObject  {
       ^
/.../roottest/root/tree/cache/Event.h:103:7: note: previous definition is here
class Event : public TObject {
      ^
In file included from test_Persistency1_C_ACLiC_dict dictionary payload:7:
./test_Persistency1.C:86:8: error: no member named 'm_evt' in 'Event'
    d->m_evt = d->m_run = i;