Revert "std::move is redundant and can prevent NRVO."
This reverts commit 12c23dd8094a5d660bc6c5b334d8c809144579a1.

At least one compiler setup requires the std::move:

ROOT-performance-centos7-multicore/default which has gcc 4.8 ....

https://epsft-jenkins.cern.ch/job/root-pullrequests-build/60327/console

 /data/sftnight/workspace/root-pullrequests-build/root/core/thread/src/TReentrantRWLock.cxx: In instantiation of ‘std::unique_ptr<ROOT::TVirtualRWMutex::State> ROOT::TReentrantRWLock<MutexT, RecurseCountsT>::GetStateBefore() [with MutexT = ROOT::TSpinMutex; RecurseCountsT = ROOT::Internal::RecurseCounts]’:
 /data/sftnight/workspace/root-pullrequests-build/root/core/thread/src/TReentrantRWLock.cxx:381:16:   required from here
 /data/sftnight/workspace/root-pullrequests-build/root/core/thread/src/TReentrantRWLock.cxx:276:11: error: cannot bind ‘std::unique_ptr<{anonymous}::TReentrantRWLockState<ROOT::TSpinMutex, ROOT::Internal::RecurseCounts>, std::default_delete<{anonymous}::TReentrantRWLockState<ROOT::TSpinMutex, ROOT::Internal::RecurseCounts> > >’ lvalue to ‘std::unique_ptr<{anonymous}::TReentrantRWLockState<ROOT::TSpinMutex, ROOT::Internal::RecurseCounts>, std::default_delete<{anonymous}::TReentrantRWLockState<ROOT::TSpinMutex, ROOT::Internal::RecurseCounts> > >&&’
     return pState;
            ^
 In file included from /usr/include/c++/4.8.2/memory:81:0,
                  from /data/sftnight/workspace/root-pullrequests-build/build/include/TVirtualMutex.h:27,
                  from /data/sftnight/workspace/root-pullrequests-build/build/include/TVirtualRWMutex.h:26,
                  from /data/sftnight/workspace/root-pullrequests-build/build/include/ROOT/TReentrantRWLock.hxx:18,
                  from /data/sftnight/workspace/root-pullrequests-build/root/core/thread/src/TReentrantRWLock.cxx:34:
 /usr/include/c++/4.8.2/bits/unique_ptr.h:169:2: error:   initializing argument 1 of ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = {anonymous}::TReentrantRWLockState<ROOT::TSpinMutex, ROOT::Internal::RecurseCounts>; _Ep = std::default_delete<{anonymous}::TReentrantRWLockState<ROOT::TSpinMutex, ROOT::Internal::RecurseCounts> >; <template-parameter-2-3> = void; _Tp = ROOT::TVirtualRWMutex::State; _Dp = std::default_delete<ROOT::TVirtualRWMutex::State>]’
   unique_ptr(unique_ptr<_Up, [ 68%] Built target unordered_multisetDict
 [ 68%] Linking CXX shared library ../../lib/libmultimap2Dict.so
 _Ep>&& __u) noexcept
   ^