Fix several potential compilation errors
Fix several potential compilation errors like:
  error C2440: 'initializing': cannot convert from 'const char [5]' to 'char *'
when compiling with the `/permissive-` flag